import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import { LanguageProvider } from "./context/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://planb-fx.com';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'PlanB FX',
    template: '%s | PlanB FX',
  },
  description: 'Custom Interactive Experiences',
  keywords: [
    'PlanB FX',
    'planbfx',
    'planb-fx',
    'Plan B',
    'plan b',
    'PlanB FX Studio',
    'VFX Studio',
    'Visual Effects Studio',
    'Post Production Studio',
    'Film Post Production',
    'Commercial Post Production',
    'CGI Studio',
    'CGI for commercials',
    'Motion Graphics Studio',
    'Motion Design',
    '3D Animation Studio',
    '3D Rendering',
    'Product Visualization',
    'Product CGI',
    'Digital Compositing',
    'VFX compositing',
    'Video editing studio',
    'Cinematic VFX',
    'VFX for branded content',
    'VFX studio for brands',
    'VFX studio for agencies',
    'creative studio for commercials',
    'post production for agencies',
    'CGI studio worldwide',
    'remote VFX studio',
    'VFX outsourcing studio',
    'VFX studio Costa Rica',
    'post production Costa Rica',
    'motion graphics Costa Rica',
    '3D animation Costa Rica',
    'CGI Costa Rica',
    'video production Costa Rica',
    'creative studio Costa Rica',
    'VFX studio Latin America',
    'post production Latin America',
    'cinematic post production',
    'premium visual effects',
    'creative VFX studio',
    'boutique post production studio',
    'cinematic motion design',
    'freelance VFX team',
    'VFX production services',
    'estudio de efectos visuales',
    'estudio VFX',
    'efectos visuales para cine',
    'efectos visuales para comerciales',
    'postproducción audiovisual',
    'estudio de postproducción',
    'CGI profesional',
    'animación 3D',
    'renderizado 3D',
    'motion graphics',
    'motion design',
    'composición digital',
    'composición VFX',
    'tracking y matchmove',
    'rotoscopia profesional',
    'efectos visuales cinematográficos',
    'visuales para eventos',
    'visuales para conciertos',
    'visuales para festivales',
    'visuales para DJs',
    'visuales para música electrónica',
    'visuales para house',
    'visuales para tech house',
    'visuales para techno',
    'visuales para raves',
    'VJ Costa Rica',
    'VJ para eventos',
    'VJ para festivales',
    'VJ para clubs',
    'VJ para fiestas',
    'visuales para sets de DJ',
    'loops visuales para DJs',
    'contenido visual para escenarios',
    'stage visuals',
    'experiencias inmersivas',
    'experiencias audiovisuales inmersivas',
    'arte interactivo',
    'instalaciones interactivas',
    'arte digital',
    'diseño de experiencias',
    'experiencias sensoriales',
    'proyecciones inmersivas',
    'contenido interactivo para eventos',
    'creative technology',
    'visual art experience',
    'video mapping Costa Rica',
    'mapping para eventos',
    'proyección para eventos',
    'contenido para pantallas LED',
    'contenido para escenarios',
    'diseño audiovisual para eventos',
    'show audiovisual',
    'producción audiovisual para eventos',
    'diseño de visuales para eventos',
    'producción de visuales en vivo',
    'eventos corporativos audiovisuales',
    'producción audiovisual corporativa',
    'contenido audiovisual para empresas',
    'motion graphics corporativo',
    'visuales para conferencias',
    'contenido para lanzamientos de marca',
    'activaciones de marca',
    'experiencias interactivas para marcas',
    'producción creativa para eventos corporativos',
    'contenido para stands y ferias',
    'producción audiovisual Costa Rica',
    'estudio audiovisual Costa Rica',
    'visuales para eventos Costa Rica',
    'VJ San José Costa Rica',
    'video mapping San José Costa Rica',
    'visuales para conciertos Costa Rica',
    'producción de eventos audiovisuales Costa Rica',
    'estudio creativo Costa Rica',
    'visuales para festivales Costa Rica',
    'experiencias inmersivas Costa Rica',
    'producción audiovisual Latinoamérica',
    'visuales para eventos Latinoamérica',
    'VJ Latinoamérica',
    'visual effects studio',
    'VFX studio',
    'post production studio',
    'film post production',
    'commercial post production',
    'CGI studio',
    'cinematic VFX',
    'photorealistic CGI',
    '3D animation studio',
    '3D rendering services',
    'motion graphics studio',
    'motion design studio',
    'VFX compositing',
    'rotoscoping services',
    'matchmove and tracking',
    'cleanup VFX',
    'visual effects for advertising',
    'live visuals for events',
    'VJ services',
    'VJ for events',
    'VJ for festivals',
    'VJ for clubs',
    'visuals for DJs',
    'visuals for electronic music',
    'house music visuals',
    'tech house visuals',
    'techno visuals',
    'electronic music visuals',
    'rave visuals',
    'festival stage visuals',
    'DJ visuals content',
    'VJ loops',
    'animated visuals for DJs',
    'stage visuals production',
    'real-time visuals',
    'immersive experiences',
    'immersive audiovisual experiences',
    'interactive art',
    'interactive installations',
    'digital art studio',
    'immersive projections',
    'creative technology studio',
    'experiential design',
    'interactive visuals',
    'multimedia installations',
    'immersive event design',
    'video mapping services',
    'projection mapping',
    'event projection design',
    'LED screen content',
    'LED visuals production',
    'event visual production',
    'audiovisual show design',
    'event visuals design',
    'concert visuals production',
    'stage design visuals',
    'corporate event visuals',
    'corporate audiovisual production',
    'brand activations',
    'experiential marketing visuals',
    'conference visuals production',
    'product launch visuals',
    'corporate motion graphics',
    'event branding visuals',
    'interactive brand experiences',
    'creative production studio',
    'VFX studio Costa Rica',
    'post production Costa Rica',
    'live visuals Costa Rica',
    'VJ Costa Rica',
    'video mapping Costa Rica',
    'audiovisual production Costa Rica',
    'event visuals Costa Rica',
    'immersive experiences Costa Rica',
    'visual production Latin America',
    'VJ Latin America',
    'live visuals Latin America',
    'audiovisual studio Latin America',
    'video mapping Latin America',
    'Custom Interactive Experiences',
    'Live Painting',
    'Artificial Mirage',
    'Audio Reactive Art',
    'Interactive Branding',
    'Logo Waterfall',
    'Projection Mapping',
    'Customized Experience',
    'Dibujo en Vivo',
    'Espejismo Artificial',
    'Arte Audio Reactivo',
    'Anuncios Interactivos',
    'Cascada de Logos',
    'Mapping y Control Visual Expresivo',
    'Experiencia Personalizada',
    'events',
    'festivals',
  ],
  openGraph: {
    title: 'PlanB FX',
    description: 'Custom Interactive Experiences',
    type: 'website',
    locale: 'en_US',
    alternateLocale: 'es_ES',
    url: SITE_URL,
  },
  twitter: {
    card: 'summary_large_image',
  },
  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  manifest: "/site.webmanifest",
};

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'PlanB FX',
  alternateName: ['planbfx', 'planb-fx', 'Plan B FX', 'Plan B', 'PlanB FX Studio'],
  url: SITE_URL,
  description: 'VFX studio, live visuals for DJs and festivals, video mapping, motion graphics, interactive art and immersive experiences. Costa Rica and Latin America.',
  email: 'info@planb-fx.com',
  sameAs: ['https://www.instagram.com/planb_fx/'],
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'San José',
    addressCountry: 'CR',
  },
  areaServed: [
    { '@type': 'Country', name: 'Costa Rica' },
    { '@type': 'Place', name: 'Latin America' },
  ],
  serviceType: ['VFX', 'Live Visuals', 'Video Mapping', 'Motion Graphics', 'Interactive Art', 'Immersive Experiences'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100dvh] w-full m-0 p-0 bg-black overflow-x-hidden`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <LanguageProvider>
          <SmoothScroll>{children}</SmoothScroll>
        </LanguageProvider>
      </body>
    </html>
  );
}
